version: '3.9'
services:
  jira:
    container_name: jira
    image: atlassian/jira-software:latest
    restart: unless-stopped
    volumes:
      - jira_data:/var/atlassian/application-data/jira
    environment:
      - ATL_PROXY_NAME=jira.yourserver.co.uk # used for reverse proxy
      - ATL_PROXY_PORT=80 # used for reverse proxy
      
volumes:
  jira_data:
